name: CI-CD PolyglotCaptions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  #########################################################
  #   CI JOB
  #########################################################
  ci:
    runs-on: ubuntu-latest
    env:
      USE_DB_STUB: "true"    # <---- THIS DISABLES REAL AZURE SQL IN CI

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Remove real DB module for CI
        run: |
          rm app/db/db.py
          mv app/db/db_stub.py app/db/db.py

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest pytest-cov

      - name: Lint
        run: |
          flake8 app \
            --exclude=app/.venv,*/venv,*/.venv \
            --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Run tests + coverage
        run: |
          pytest --cov=app --cov-report=xml --cov-report=term

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml


  #########################################################
  #   CD JOB â€“ BUILD + PUSH DOCKER IMAGE
  #########################################################
  cd:
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t gvega2212/polyglotcaptions:latest .

      - name: Push Docker image
        run: |
          docker push gvega2212/polyglotcaptions:latest
